version: "3.1"

services:

  visualizer:
    image: dockersamples/visualizer
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  ubuntu:
    image: rastasheep/ubuntu-sshd:16.04
    ports:
      - "2222:22"
    deploy:
      mode: global

# networks:
#   application:
#     driver: overlay
#     driver_opts:
#       encrypted: ""
#     internal: true
#   database:
#     driver: overlay
#     driver_opts:
#       encrypted: ""
#     internal: true
